### PR TITLE
Added properties for edges

### PR DESCRIPTION
**Pull request by dstuebe**
Adding properties for edges makes the graph more powerful in line [TitanDB](http://s3.thinkaurelius.com/docs/titan/0.5.3/getting-started.html) and other graph database models.
It could use the same mixin approach as the vertex, but I don't think that is necessary.

### CODE REVIEW

**Comment by dstuebe** [comment]
I had to run 'bundle update mutant' to install, but it seems I have broken the build and I am not sure how to fix it. If you are interested in merging this PR please let me know how to repair the build.

**Comment by kevinrutherford** [comment]
Hi David, thanks for taking the time to do this!  Mutant isn't needed, so I guess the best thing would be just to remove it from the Gemfile.

**Comment by dstuebe** [comment]
Okay - I will ditch mutant. Do you want to keep two separate PR's for these features or should I roll them up together? I have also added some simple hooks to RubyGraphViz to render a DAG. Are you interested in merging that as well?

**Comment by kevinrutherford** [comment]
Let's keep these pull requests separate for now. And maybe make a third for the RubyGraphViz hooks?

**Comment by dstuebe** [comment]
Great will do.

**Comment by dstuebe** [comment]
Sigh - I am still new to bundler / gemfiles. I will try and sort this out tomorrow.

**Pull request merged**
